//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBusiness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public Delivery()
        {
            this.PurchaseDelivery = new HashSet<PurchaseDelivery>();
        }
    
        public int Id { get; set; }
        public string CarriageCode { get; set; }
        public string BillCode { get; set; }
        public string GoodsName { get; set; }
        public float Quantity { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Provider { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string Receiver { get; set; }
        public string Picture { get; set; }
    
        public virtual ICollection<PurchaseDelivery> PurchaseDelivery { get; set; }
    }
}
