//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBusiness.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyBusinessModelContainer : DbContext
    {
        public MyBusinessModelContainer()
            : base("name=MyBusinessModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PurchaseContract> PurchaseContractSet { get; set; }
        public DbSet<Partner> PartnerSet { get; set; }
        public DbSet<Delivery> DeliverySet { get; set; }
        public DbSet<PurchaseTarget> PurchaseTargetSet { get; set; }
        public DbSet<PurchaseDelivery> PurchaseDeliverySet { get; set; }
        public DbSet<PartnerDocument> PartnerDocuments { get; set; }
    }
}
