//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBusiness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseContract
    {
        public PurchaseContract()
        {
            this.PurchaseTarget = new HashSet<PurchaseTarget>();
            this.Delivery = new HashSet<PurchaseDelivery>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime SignDate { get; set; }
        public int PartnerId { get; set; }
        public Nullable<System.DateTime> DeliveryEndDate { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
    
        public virtual ICollection<PurchaseTarget> PurchaseTarget { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<PurchaseDelivery> Delivery { get; set; }
    }
}
